export const SHOW_APP_LOADING = 'SHOW_APP_LOADING';
export const SHOW_APP_MESSAGE = 'SHOW_APP_MESSAGE';
export const HIDE_APP_MESSAGE = 'HIDE_APP_MESSAGE';

export const GET_SCOREBOARD = 'GET_SCOREBOARD';
export const GET_SCOREBOARD_SUCCESS = 'GET_SCOREBOARD_SUCCESS';
